### PR TITLE
95257346 cleanup oe

### PR DESCRIPTION
**Pull request by djvern**
A few comments:
- I've enabled multiple images and put them into their own vertical tab field groups in the edit form and the view mode.
- I've used the same name for field groups for both the edit form and the view mode, which means that the feature now captures 2 groups because in the edit form we're using vertical tabs and in the view mode I'm using default fieldsets. Drupal assigns unique identifiers based on the group type, so for example we now have:
    - **group_event_image|node|event|default** and;
    - **group_event_image|node|event|form**
- field_event_date_end is no longer a required field, as requested by this bug: [#95858288](https://www.pivotaltracker.com/story/show/95858288)
- there are currently no required fields for person, so you can save a person without any name being generated. Should for example Given Name be required?

### CODE REVIEW

**Comment by djvern** [comment]
@jorgelopezlago I forgot to mention about the dates - the office hours module does not output the opening times in ISO format, but is this an issue as Alex is formatting the dates at the API level?

**Comment by jorgelopezlago** [comment]
@djvern Alex is working on the dates formats for the date fields. The office hours fields may require a separate treatment. I will add further notes once I have seen it in detail.

**Comment by jorgelopezlago** [comment]
To delete from file *local-openevent.make*:
`; if drupal-org-core.make is not existent: project[drupal][version] = "7.18"`

**Comment by jorgelopezlago** [comment]
Update README.md file for the installation instructions. If we add standard installation instructions step by step we must include the required steps to create settings.php and files between steps 5 and 6.

**Proposal:**
5. Create settings.php.
Copy the default.settings.php file and save the new file as settings.php in the `<root>/sites/default` directory. 
*Note: Do not simply rename the file. The Drupal installer needs both files.*
Change the permissions of settings.php to allow the install script to edit the file.
Refer to https://www.drupal.org/documentation/install/settings-file for detailed instructions.
6. Create the files directory
Change the permissions of the sites/default directory to allow the install script to create a files directory. Alternatively, you can create the sites/default/files directory yourself, and give the webuser permissions to write to it.
Refer to https://www.drupal.org/documentation/install/settings-file for detailed instructions.

**Comment by jorgelopezlago** [comment]
syslog module is still enabled on install. Remove it from openevent.info.

**Comment by jorgelopezlago** [comment]
Remove the following lines
`// Disable bartik theme`
`  theme_disable(array('bartik'));`
from openevent.install as they are not required after declaring *seven* as the default theme.

**Comment by jorgelopezlago** [comment]
Fix the links in the description for the image field in Events. *Event* links to schema.org/image instead of schema.org/Event.

**Comment by jorgelopezlago** [comment]
According to the international standard ISO 8601, Monday is the first day of the week ending with Sunday as the seventh day of the week.

Update the field display for *opening hours* in *Place content type* to assign Monday as the first day of the week (/admin/structure/types/manage/place/display).

**Comment by jorgelopezlago** [comment]
Update the field display for *Prefix* in *Person content type* so it is not displayed as a link to the corresponding taxonomy term (admin/structure/types/manage/person/display). It must be displayed as *plain text*.

**Comment by jorgelopezlago** [comment]
We use `[node:field_person_name_given] [node:field_person_name_family]` for the Person nodes title for convenience (and laziness). In other languages the family name is composed of father and mother surnames concatenated, which guarantees less coincidences, but in English the potential duplicates are abundant.
In order to manage this and reduce the chances automatically change the configuration of auto label (admin/structure/types/manage/person/auto_label) to the following: `[node:field_person_name_given] [node:field_person_name_middle] [node:field_person_name_family]`. This way if the middle name is not used it is not displayed gracefully.

**Comment by alexb-cogapp** [comment]
>According to the international standard ISO 8601, Monday is the first day of the week ending with Sunday as the seventh day of the week.

>Update the field display for opening hours in Place content type to assign Monday as the first day of the week (/admin/structure/types/manage/place/display).

If this changes the index which days are stored using, we'll need to update code which maps the office hours module to Schema.org, as this currently relies on 0=>Sunday etc.

The output-mapped content doesn't use these indexes at all, instead taking this form:

    [{
      "dayOfWeek": "http://purl.org/goodrelations/v1#Sunday",
      "opens": "10:00:00",
      "closes": "17:00:00"
    },
    {
      "dayOfWeek": "http://purl.org/goodrelations/v1#Monday",
      "opens": "09:00:00",
      "closes": "18:00:00"
    }
    ...]

Given this, is updating Drupal's internal representation a priority?

**Comment by tassosk-cogapp** [comment]
@jorgelopezlago instructions are for developers that want to contribute and as such contains the command line steps. Running `drush si` takes care of `settings.php` and `files`.

**Comment by djvern** [comment]
Regarding removing the 
`Disable bartik theme`
`theme_disable(array('bartik'));`
without this line the Bartik theme is still enabled (but not set as default). If this is ok then I will remove..

**Comment by jorgelopezlago** [comment]
@djvern No. Bartik is assigned as default theme on the installation profile. And we assign seven instead.

**Comment by jorgelopezlago** [comment]
@djvern Yes, probably better to leave the line in for Bartik.

**Comment by jorgelopezlago** [comment]
@tassosk-cogapp OK. Agreed.

**Comment by jorgelopezlago** [comment]
@alexb-cogapp The index assigned for the first day of the week is configured per field. But I assume that the days are still 0=>Sunday, 7=> Saturday. Something to check.

**Pull request merged**
