### PR TITLE
95252412 api documentation

### PR DESCRIPTION
**Pull request by samueljmurray**

### CODE REVIEW

**Comment by tassosk-cogapp** [comment]
Hi @samueljmurray my comments below:

Fields that are not working at the filtering level

**Event**
endDate
startDate
doorTime
duration
image
All relation fields


**Person**
image
performerin
sameas

**Place**
image
address
geo
openingHoursSpecification
containedIn

I do not see a purpose to list which roles have what permissions. It is implied that what is presented in this list has read permissions at the moment for the anonymous user and that is all that is needed to be known by an outsider to the system.

**Comment by samueljmurray** [comment]
@tassosk-cogapp good point about the filtering. I'll move the table of properties to a new section that documents the expected output for each endpoint rather than the available filtering options.

Is there a simple way to determine whether or not a property is available as a filter or not? A method the docs could call?

For the permissions, I do see a purpose. People who implement OpenEvent may want to make particular resources available to certain roles and not others. Showing this in the documentation would allow users with higher privileges the ability to see in the documentation which endpoints users with lower privileges can't access. There isn't value in there for us, but I think there definitely could be for other people who implement OpenEvent.

**Comment by jorgelopezlago** [comment]
General comments based on a paper code review of **oe_rest_api_doc.module** (note that the review was done on code a couple of days old and some remarks may not be applicable at the moment of this comment):
- Add @file headers to Drupal PHP files.
- Function **oe_rest_api_doc_page($format = '')**
 - Document @param
 - Document @return
 - This is a callback function for a menu item, add it to the @ingroup callbacks
 - The function builds and alters the $page array, but some of the output could be extracted to blocks to give more flexibility and overriding possibilities to the module

**Comment by tassosk-cogapp** [comment]
@samueljmurray there isn't a function for that I'm afraid. Generally we have not implemented any code to handle special cases that contain time, relations, address and multivalued fields that are not understandable by drupal. The canonical list of what is not supported is the one included above.

I still think that permissions should not be public facing information but that is just me. If no one else feels that same then I do not have any problem with it.

**Comment by samueljmurray** [comment]
@jorgelopezlago @tassosk-cogapp I've made some changes:

I've added the extra documentation you mentioned Jorge

*"The function builds and alters the $page array, but some of the output could be extracted to blocks to give more flexibility and overriding possibilities to the module"*
--> Yes it could but I think we should leave that for a future improvement

*"What are the possible values valid for $format? Are those strings? Can they be upper case?"*
--> These are strings, uppercase or lowercase is fine. Once we made more data formats available (XML, RDF etc.) links to view the documentation for those endpoints will appear at the top of the page, linking to /api/doc/xml, /api/doc/rdf etc.

*"Make sure the string manipulation for 'schema:' treatment agrees with the mapping main module"*
--> I've removed this now that the API schema mapping doesn't include 'schema:' in the property names

I've also removed the permissions from the page because I think you're both right that it is a security issue. Showing it just for the drupal root user I don't think adds any value - they can view permissions on the permissions page.

**Pull request merged**
